// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	errors "errors"
	Lattice "github.com/anduril/lattice-sdk-go/v5"
	core "github.com/anduril/lattice-sdk-go/v5/core"
	entity "github.com/anduril/lattice-sdk-go/v5/entity"
	client "github.com/anduril/lattice-sdk-go/v5/entity/client"
	oauth2 "github.com/anduril/lattice-sdk-go/v5/entity/oauth2"
	internal "github.com/anduril/lattice-sdk-go/v5/internal"
	objects "github.com/anduril/lattice-sdk-go/v5/objects"
	option "github.com/anduril/lattice-sdk-go/v5/option"
	taskclient "github.com/anduril/lattice-sdk-go/v5/task/client"
)

type Client struct {
	Objects *objects.Client
	Entity  *client.Client
	Task    *taskclient.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	oauthTokenProvider := core.NewOAuthTokenProvider(
		options.ClientID,
		options.ClientSecret,
	)
	authOptions := *options
	authClient := oauth2.NewClient(
		&authOptions,
	)
	options.SetTokenGetter(func() (string, error) {
		return oauthTokenProvider.GetOrFetch(func() (string, int, error) {
			response, err := authClient.GetToken(context.Background(), &entity.GetTokenRequest{
				ClientID: Lattice.String(
					options.ClientID,
				),
				ClientSecret: Lattice.String(
					options.ClientSecret,
				),
			})
			if err != nil {
				return "", 0, err
			}
			if response.AccessToken == "" {
				return "", 0, errors.New(
					"oauth response missing access token",
				)
			}
			expiresIn := core.DefaultExpirySeconds
			if response.ExpiresIn != nil {
				expiresIn = *response.ExpiresIn
			}
			return response.AccessToken, expiresIn, nil
		})
	})
	return &Client{
		Objects: objects.NewClient(options),
		Entity:  client.NewClient(options),
		Task:    taskclient.NewClient(options),
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
