// Code generated by Fern. DO NOT EDIT.

package objects_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	Lattice "github.com/anduril/lattice-sdk-go/v4"
	client "github.com/anduril/lattice-sdk-go/v4/client"
	option "github.com/anduril/lattice-sdk-go/v4/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestObjectsListObjectsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &Lattice.ListObjectsRequest{
		Prefix: Lattice.String(
			"prefix",
		),
		SinceTimestamp: Lattice.Time(
			Lattice.MustParseDateTime(
				"2024-01-15T09:30:00Z",
			),
		),
		PageToken: Lattice.String(
			"pageToken",
		),
		AllObjectsInMesh: Lattice.Bool(
			true,
		),
		MaxPageSize: Lattice.Int(
			1,
		),
	}
	_, invocationErr := client.Objects.ListObjects(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestObjectsListObjectsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestObjectsListObjectsWithWireMock", "GET", "/api/v1/objects", map[string]string{"prefix": "prefix", "sinceTimestamp": "2024-01-15T09:30:00Z", "pageToken": "pageToken", "allObjectsInMesh": "true", "maxPageSize": "1"}, 1)
}

func TestObjectsGetObjectWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &Lattice.GetObjectRequest{}
	_, invocationErr := client.Objects.GetObject(
		context.TODO(),
		"objectPath",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestObjectsGetObjectWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestObjectsGetObjectWithWireMock", "GET", "/api/v1/objects/objectPath", nil, 1)
}

func TestObjectsUploadObjectWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := bytes.NewReader(
		[]byte(""),
	)
	_, invocationErr := client.Objects.UploadObject(
		context.TODO(),
		"<objectPath>",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestObjectsUploadObjectWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestObjectsUploadObjectWithWireMock", "POST", "/api/v1/objects/%3CobjectPath%3E", nil, 1)
}

func TestObjectsDeleteObjectWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	invocationErr := client.Objects.DeleteObject(
		context.TODO(),
		"objectPath",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestObjectsDeleteObjectWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestObjectsDeleteObjectWithWireMock", "DELETE", "/api/v1/objects/objectPath", nil, 1)
}

func TestObjectsGetObjectMetadataWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	invocationErr := client.Objects.GetObjectMetadata(
		context.TODO(),
		"objectPath",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestObjectsGetObjectMetadataWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestObjectsGetObjectMetadataWithWireMock", "HEAD", "/api/v1/objects/objectPath", nil, 1)
}
