// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/anduril/lattice-sdk-go/v5/core"
	internal "github.com/anduril/lattice-sdk-go/v5/internal"
	tasks "github.com/anduril/lattice-sdk-go/v5/task/tasks"
)

type Client struct {
	Tasks *tasks.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Tasks:   tasks.NewClient(options),
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
