// Code generated by Fern. DO NOT EDIT.

package task

import (
	core "github.com/anduril/lattice-sdk-go/v5/core"
	internal "github.com/anduril/lattice-sdk-go/v5/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	400: func(apiError *core.APIError) error {
		return &BadRequestError{
			APIError: apiError,
		}
	},
	401: func(apiError *core.APIError) error {
		return &UnauthorizedError{
			APIError: apiError,
		}
	},
	404: func(apiError *core.APIError) error {
		return &NotFoundError{
			APIError: apiError,
		}
	},
}
