// Code generated by Fern. DO NOT EDIT.

package Lattice

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/anduril/lattice-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	taskCreationFieldTaskID              = big.NewInt(1 << 0)
	taskCreationFieldDisplayName         = big.NewInt(1 << 1)
	taskCreationFieldDescription         = big.NewInt(1 << 2)
	taskCreationFieldSpecification       = big.NewInt(1 << 3)
	taskCreationFieldAuthor              = big.NewInt(1 << 4)
	taskCreationFieldRelations           = big.NewInt(1 << 5)
	taskCreationFieldIsExecutedElsewhere = big.NewInt(1 << 6)
	taskCreationFieldInitialEntities     = big.NewInt(1 << 7)
)

type TaskCreation struct {
	// If non-empty, will set the requested Task ID, otherwise will generate a new random
	// GUID. Will reject if supplied Task ID does not match [A-Za-z0-9_-.]{5,36}.
	TaskID *string `json:"taskId,omitempty" url:"-"`
	// Human readable display name for this Task, should be short (<100 chars).
	DisplayName *string `json:"displayName,omitempty" url:"-"`
	// Longer, free form human readable description of this Task.
	Description *string `json:"description,omitempty" url:"-"`
	// The path for the Protobuf task definition, and the complete task data.
	Specification *GoogleProtobufAny `json:"specification,omitempty" url:"-"`
	Author        *Principal         `json:"author,omitempty" url:"-"`
	// Any relationships associated with this Task, such as a parent Task or an assignee
	// this Task is designated to for execution.
	Relations *Relations `json:"relations,omitempty" url:"-"`
	// If set, then the service will not trigger execution of this task on an agent. Useful
	// for when ingesting tasks from an external system that is triggering execution of tasks
	// on agents.
	IsExecutedElsewhere *bool `json:"isExecutedElsewhere,omitempty" url:"-"`
	// Indicates an initial set of entities that can be used to execute an entity aware
	// task. For example, an entity Objective, an entity Keep In Zone, etc.
	InitialEntities []*TaskEntity `json:"initialEntities,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TaskCreation) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTaskID sets the TaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskCreation) SetTaskID(taskID *string) {
	t.TaskID = taskID
	t.require(taskCreationFieldTaskID)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskCreation) SetDisplayName(displayName *string) {
	t.DisplayName = displayName
	t.require(taskCreationFieldDisplayName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskCreation) SetDescription(description *string) {
	t.Description = description
	t.require(taskCreationFieldDescription)
}

// SetSpecification sets the Specification field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskCreation) SetSpecification(specification *GoogleProtobufAny) {
	t.Specification = specification
	t.require(taskCreationFieldSpecification)
}

// SetAuthor sets the Author field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskCreation) SetAuthor(author *Principal) {
	t.Author = author
	t.require(taskCreationFieldAuthor)
}

// SetRelations sets the Relations field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskCreation) SetRelations(relations *Relations) {
	t.Relations = relations
	t.require(taskCreationFieldRelations)
}

// SetIsExecutedElsewhere sets the IsExecutedElsewhere field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskCreation) SetIsExecutedElsewhere(isExecutedElsewhere *bool) {
	t.IsExecutedElsewhere = isExecutedElsewhere
	t.require(taskCreationFieldIsExecutedElsewhere)
}

// SetInitialEntities sets the InitialEntities field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskCreation) SetInitialEntities(initialEntities []*TaskEntity) {
	t.InitialEntities = initialEntities
	t.require(taskCreationFieldInitialEntities)
}

var (
	getTaskRequestFieldTaskID = big.NewInt(1 << 0)
)

type GetTaskRequest struct {
	// ID of task to return
	TaskID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetTaskRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetTaskID sets the TaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTaskRequest) SetTaskID(taskID string) {
	g.TaskID = taskID
	g.require(getTaskRequestFieldTaskID)
}

var (
	agentListenerFieldAgentSelector = big.NewInt(1 << 0)
)

type AgentListener struct {
	// Selector criteria to determine which Agent Tasks the agent receives
	AgentSelector *EntityIDsSelector `json:"agentSelector,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AgentListener) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAgentSelector sets the AgentSelector field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentListener) SetAgentSelector(agentSelector *EntityIDsSelector) {
	a.AgentSelector = agentSelector
	a.require(agentListenerFieldAgentSelector)
}

var (
	taskQueryFieldPageToken       = big.NewInt(1 << 0)
	taskQueryFieldParentTaskID    = big.NewInt(1 << 1)
	taskQueryFieldStatusFilter    = big.NewInt(1 << 2)
	taskQueryFieldUpdateTimeRange = big.NewInt(1 << 3)
)

type TaskQuery struct {
	// If set, returns results starting from the given pageToken.
	PageToken *string `json:"pageToken,omitempty" url:"-"`
	// If present matches Tasks with this parent Task ID.
	// Note: this is mutually exclusive with all other query parameters, for example, either provide parent task ID, or
	// any of the remaining parameters, but not both.
	ParentTaskID *string                `json:"parentTaskId,omitempty" url:"-"`
	StatusFilter *TaskQueryStatusFilter `json:"statusFilter,omitempty" url:"-"`
	// If provided, only provides Tasks updated within the time range.
	UpdateTimeRange *TaskQueryUpdateTimeRange `json:"updateTimeRange,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TaskQuery) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetPageToken sets the PageToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskQuery) SetPageToken(pageToken *string) {
	t.PageToken = pageToken
	t.require(taskQueryFieldPageToken)
}

// SetParentTaskID sets the ParentTaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskQuery) SetParentTaskID(parentTaskID *string) {
	t.ParentTaskID = parentTaskID
	t.require(taskQueryFieldParentTaskID)
}

// SetStatusFilter sets the StatusFilter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskQuery) SetStatusFilter(statusFilter *TaskQueryStatusFilter) {
	t.StatusFilter = statusFilter
	t.require(taskQueryFieldStatusFilter)
}

// SetUpdateTimeRange sets the UpdateTimeRange field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskQuery) SetUpdateTimeRange(updateTimeRange *TaskQueryUpdateTimeRange) {
	t.UpdateTimeRange = updateTimeRange
	t.require(taskQueryFieldUpdateTimeRange)
}

// Response streamed to an agent containing task actions to perform.
//
// This message is streamed from Tasks API to agents and contains one of three
// possible requests: execute a task, cancel a task, or complete a task. The agent
// should process these requests according to its capabilities and report status
// updates back to Tasks API using the UpdateStatus endpoint.
//
// Multiple responses may be sent for different tasks, and the agent should maintain
// the connection to receive ongoing task requests. The connection may also be used
// for heartbeat messages to ensure the agent is still responsive.
var (
	agentRequestFieldExecuteRequest  = big.NewInt(1 << 0)
	agentRequestFieldCancelRequest   = big.NewInt(1 << 1)
	agentRequestFieldCompleteRequest = big.NewInt(1 << 2)
)

type AgentRequest struct {
	ExecuteRequest  *ExecuteRequest  `json:"executeRequest,omitempty" url:"executeRequest,omitempty"`
	CancelRequest   *CancelRequest   `json:"cancelRequest,omitempty" url:"cancelRequest,omitempty"`
	CompleteRequest *CompleteRequest `json:"completeRequest,omitempty" url:"completeRequest,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentRequest) GetExecuteRequest() *ExecuteRequest {
	if a == nil {
		return nil
	}
	return a.ExecuteRequest
}

func (a *AgentRequest) GetCancelRequest() *CancelRequest {
	if a == nil {
		return nil
	}
	return a.CancelRequest
}

func (a *AgentRequest) GetCompleteRequest() *CompleteRequest {
	if a == nil {
		return nil
	}
	return a.CompleteRequest
}

func (a *AgentRequest) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AgentRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetExecuteRequest sets the ExecuteRequest field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentRequest) SetExecuteRequest(executeRequest *ExecuteRequest) {
	a.ExecuteRequest = executeRequest
	a.require(agentRequestFieldExecuteRequest)
}

// SetCancelRequest sets the CancelRequest field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentRequest) SetCancelRequest(cancelRequest *CancelRequest) {
	a.CancelRequest = cancelRequest
	a.require(agentRequestFieldCancelRequest)
}

// SetCompleteRequest sets the CompleteRequest field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentRequest) SetCompleteRequest(completeRequest *CompleteRequest) {
	a.CompleteRequest = completeRequest
	a.require(agentRequestFieldCompleteRequest)
}

func (a *AgentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentRequest) MarshalJSON() ([]byte, error) {
	type embed AgentRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentRequest) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// Allocation contains a list of agents allocated to a task.
var (
	allocationFieldActiveAgents = big.NewInt(1 << 0)
)

type Allocation struct {
	// Agents actively being utilized in a task.
	ActiveAgents []*Agent `json:"activeAgents,omitempty" url:"activeAgents,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *Allocation) GetActiveAgents() []*Agent {
	if a == nil {
		return nil
	}
	return a.ActiveAgents
}

func (a *Allocation) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *Allocation) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetActiveAgents sets the ActiveAgents field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Allocation) SetActiveAgents(activeAgents []*Agent) {
	a.ActiveAgents = activeAgents
	a.require(allocationFieldActiveAgents)
}

func (a *Allocation) UnmarshalJSON(data []byte) error {
	type unmarshaler Allocation
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = Allocation(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *Allocation) MarshalJSON() ([]byte, error) {
	type embed Allocation
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *Allocation) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// The request to cancel a task.
//
//	Contains the task, and the assignee of the request to cancel the task.
var (
	cancelRequestFieldTaskID   = big.NewInt(1 << 0)
	cancelRequestFieldAssignee = big.NewInt(1 << 1)
)

type CancelRequest struct {
	// The unique task ID of the task to cancel.
	TaskID *string `json:"taskId,omitempty" url:"taskId,omitempty"`
	// The assignee of the Task. Useful for agent routing where an endpoint owns multiple agents,
	//
	//	especially onBehalfOf assignees.
	Assignee *Principal `json:"assignee,omitempty" url:"assignee,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CancelRequest) GetTaskID() *string {
	if c == nil {
		return nil
	}
	return c.TaskID
}

func (c *CancelRequest) GetAssignee() *Principal {
	if c == nil {
		return nil
	}
	return c.Assignee
}

func (c *CancelRequest) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CancelRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetTaskID sets the TaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CancelRequest) SetTaskID(taskID *string) {
	c.TaskID = taskID
	c.require(cancelRequestFieldTaskID)
}

// SetAssignee sets the Assignee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CancelRequest) SetAssignee(assignee *Principal) {
	c.Assignee = assignee
	c.require(cancelRequestFieldAssignee)
}

func (c *CancelRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CancelRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CancelRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CancelRequest) MarshalJSON() ([]byte, error) {
	type embed CancelRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CancelRequest) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// The request to complete a task.
//
//	Contains the unique ID of the task to complete.
var (
	completeRequestFieldTaskID = big.NewInt(1 << 0)
)

type CompleteRequest struct {
	// ID of the task to complete.
	TaskID *string `json:"taskId,omitempty" url:"taskId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CompleteRequest) GetTaskID() *string {
	if c == nil {
		return nil
	}
	return c.TaskID
}

func (c *CompleteRequest) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CompleteRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetTaskID sets the TaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CompleteRequest) SetTaskID(taskID *string) {
	c.TaskID = taskID
	c.require(completeRequestFieldTaskID)
}

func (c *CompleteRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CompleteRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CompleteRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CompleteRequest) MarshalJSON() ([]byte, error) {
	type embed CompleteRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CompleteRequest) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	entityIDsSelectorFieldEntityIDs = big.NewInt(1 << 0)
)

type EntityIDsSelector struct {
	// Receive tasks as an assignee for one or more of the supplied entity ids.
	EntityIDs []string `json:"entityIds,omitempty" url:"entityIds,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EntityIDsSelector) GetEntityIDs() []string {
	if e == nil {
		return nil
	}
	return e.EntityIDs
}

func (e *EntityIDsSelector) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EntityIDsSelector) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetEntityIDs sets the EntityIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityIDsSelector) SetEntityIDs(entityIDs []string) {
	e.EntityIDs = entityIDs
	e.require(entityIDsSelectorFieldEntityIDs)
}

func (e *EntityIDsSelector) UnmarshalJSON(data []byte) error {
	type unmarshaler EntityIDsSelector
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EntityIDsSelector(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EntityIDsSelector) MarshalJSON() ([]byte, error) {
	type embed EntityIDsSelector
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EntityIDsSelector) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// The request to execute a task.
//
//	Contains the unique ID of the task to execute.
var (
	executeRequestFieldTask = big.NewInt(1 << 0)
)

type ExecuteRequest struct {
	// The task to execute.
	Task *Task `json:"task,omitempty" url:"task,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ExecuteRequest) GetTask() *Task {
	if e == nil {
		return nil
	}
	return e.Task
}

func (e *ExecuteRequest) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *ExecuteRequest) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetTask sets the Task field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExecuteRequest) SetTask(task *Task) {
	e.Task = task
	e.require(executeRequestFieldTask)
}

func (e *ExecuteRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ExecuteRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ExecuteRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ExecuteRequest) MarshalJSON() ([]byte, error) {
	type embed ExecuteRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ExecuteRequest) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
var (
	googleProtobufAnyFieldType = big.NewInt(1 << 0)
)

type GoogleProtobufAny struct {
	// The type of the serialized message.
	Type *string `json:"@type,omitempty" url:"@type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (g *GoogleProtobufAny) GetType() *string {
	if g == nil {
		return nil
	}
	return g.Type
}

func (g *GoogleProtobufAny) GetExtraProperties() map[string]interface{} {
	return g.ExtraProperties
}

func (g *GoogleProtobufAny) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GoogleProtobufAny) SetType(type_ *string) {
	g.Type = type_
	g.require(googleProtobufAnyFieldType)
}

func (g *GoogleProtobufAny) UnmarshalJSON(data []byte) error {
	type embed GoogleProtobufAny
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GoogleProtobufAny(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.ExtraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GoogleProtobufAny) MarshalJSON() ([]byte, error) {
	type embed GoogleProtobufAny
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, g.ExtraProperties)
}

func (g *GoogleProtobufAny) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Owner designates the entity responsible for writes of task data.
var (
	ownerFieldEntityID = big.NewInt(1 << 0)
)

type Owner struct {
	// Entity ID of the owner.
	EntityID *string `json:"entityId,omitempty" url:"entityId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *Owner) GetEntityID() *string {
	if o == nil {
		return nil
	}
	return o.EntityID
}

func (o *Owner) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *Owner) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetEntityID sets the EntityID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *Owner) SetEntityID(entityID *string) {
	o.EntityID = entityID
	o.require(ownerFieldEntityID)
}

func (o *Owner) UnmarshalJSON(data []byte) error {
	type unmarshaler Owner
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = Owner(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *Owner) MarshalJSON() ([]byte, error) {
	type embed Owner
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *Owner) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

// A Principal is an entity that has authority over this task.
var (
	principalFieldSystem     = big.NewInt(1 << 0)
	principalFieldUser       = big.NewInt(1 << 1)
	principalFieldTeam       = big.NewInt(1 << 2)
	principalFieldOnBehalfOf = big.NewInt(1 << 3)
)

type Principal struct {
	System *System `json:"system,omitempty" url:"system,omitempty"`
	User   *User   `json:"user,omitempty" url:"user,omitempty"`
	Team   *Team   `json:"team,omitempty" url:"team,omitempty"`
	// The Principal _this_ Principal is acting on behalf of.
	//
	//	Likely only populated once in the nesting (i.e. the "on_behalf_of" Principal would not have another "on_behalf_of" in most cases).
	OnBehalfOf *Principal `json:"onBehalfOf,omitempty" url:"onBehalfOf,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *Principal) GetSystem() *System {
	if p == nil {
		return nil
	}
	return p.System
}

func (p *Principal) GetUser() *User {
	if p == nil {
		return nil
	}
	return p.User
}

func (p *Principal) GetTeam() *Team {
	if p == nil {
		return nil
	}
	return p.Team
}

func (p *Principal) GetOnBehalfOf() *Principal {
	if p == nil {
		return nil
	}
	return p.OnBehalfOf
}

func (p *Principal) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *Principal) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetSystem sets the System field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Principal) SetSystem(system *System) {
	p.System = system
	p.require(principalFieldSystem)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Principal) SetUser(user *User) {
	p.User = user
	p.require(principalFieldUser)
}

// SetTeam sets the Team field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Principal) SetTeam(team *Team) {
	p.Team = team
	p.require(principalFieldTeam)
}

// SetOnBehalfOf sets the OnBehalfOf field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Principal) SetOnBehalfOf(onBehalfOf *Principal) {
	p.OnBehalfOf = onBehalfOf
	p.require(principalFieldOnBehalfOf)
}

func (p *Principal) UnmarshalJSON(data []byte) error {
	type unmarshaler Principal
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = Principal(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *Principal) MarshalJSON() ([]byte, error) {
	type embed Principal
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *Principal) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Describes the relationships associated with this task: the system assigned to
//
//	execute the task, and the parent task, if one exists.
var (
	relationsFieldAssignee     = big.NewInt(1 << 0)
	relationsFieldParentTaskID = big.NewInt(1 << 1)
)

type Relations struct {
	// The system, user, or team assigned to the task.
	Assignee *Principal `json:"assignee,omitempty" url:"assignee,omitempty"`
	// Identifies the parent task if the task is a sub-task.
	ParentTaskID *string `json:"parentTaskId,omitempty" url:"parentTaskId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *Relations) GetAssignee() *Principal {
	if r == nil {
		return nil
	}
	return r.Assignee
}

func (r *Relations) GetParentTaskID() *string {
	if r == nil {
		return nil
	}
	return r.ParentTaskID
}

func (r *Relations) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *Relations) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetAssignee sets the Assignee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Relations) SetAssignee(assignee *Principal) {
	r.Assignee = assignee
	r.require(relationsFieldAssignee)
}

// SetParentTaskID sets the ParentTaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Relations) SetParentTaskID(parentTaskID *string) {
	r.ParentTaskID = parentTaskID
	r.require(relationsFieldParentTaskID)
}

func (r *Relations) UnmarshalJSON(data []byte) error {
	type unmarshaler Relations
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = Relations(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *Relations) MarshalJSON() ([]byte, error) {
	type embed Relations
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *Relations) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Any metadata associated with the replication of a task.
var (
	replicationFieldStaleTime = big.NewInt(1 << 0)
)

type Replication struct {
	// The time by which this task should be assumed to be stale.
	StaleTime *time.Time `json:"staleTime,omitempty" url:"staleTime,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *Replication) GetStaleTime() *time.Time {
	if r == nil {
		return nil
	}
	return r.StaleTime
}

func (r *Replication) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *Replication) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetStaleTime sets the StaleTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Replication) SetStaleTime(staleTime *time.Time) {
	r.StaleTime = staleTime
	r.require(replicationFieldStaleTime)
}

func (r *Replication) UnmarshalJSON(data []byte) error {
	type embed Replication
	var unmarshaler = struct {
		embed
		StaleTime *internal.DateTime `json:"staleTime,omitempty"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = Replication(unmarshaler.embed)
	r.StaleTime = unmarshaler.StaleTime.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *Replication) MarshalJSON() ([]byte, error) {
	type embed Replication
	var marshaler = struct {
		embed
		StaleTime *internal.DateTime `json:"staleTime,omitempty"`
	}{
		embed:     embed(*r),
		StaleTime: internal.NewOptionalDateTime(r.StaleTime),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *Replication) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// System Principal representing some autonomous system.
var (
	systemFieldServiceName          = big.NewInt(1 << 0)
	systemFieldEntityID             = big.NewInt(1 << 1)
	systemFieldManagesOwnScheduling = big.NewInt(1 << 2)
)

type System struct {
	// Name of the service associated with this System.
	ServiceName *string `json:"serviceName,omitempty" url:"serviceName,omitempty"`
	// The Entity ID of the System.
	EntityID *string `json:"entityId,omitempty" url:"entityId,omitempty"`
	// Whether the System Principal (for example, an Asset) can own scheduling.
	//
	//	This means we bypass manager-owned scheduling and defer to the system
	//	Principal to handle scheduling and give us status updates for the task.
	//	Regardless of the value defined by the client, the Task Manager will
	//	determine and set this value appropriately.
	ManagesOwnScheduling *bool `json:"managesOwnScheduling,omitempty" url:"managesOwnScheduling,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *System) GetServiceName() *string {
	if s == nil {
		return nil
	}
	return s.ServiceName
}

func (s *System) GetEntityID() *string {
	if s == nil {
		return nil
	}
	return s.EntityID
}

func (s *System) GetManagesOwnScheduling() *bool {
	if s == nil {
		return nil
	}
	return s.ManagesOwnScheduling
}

func (s *System) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *System) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetServiceName sets the ServiceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *System) SetServiceName(serviceName *string) {
	s.ServiceName = serviceName
	s.require(systemFieldServiceName)
}

// SetEntityID sets the EntityID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *System) SetEntityID(entityID *string) {
	s.EntityID = entityID
	s.require(systemFieldEntityID)
}

// SetManagesOwnScheduling sets the ManagesOwnScheduling field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *System) SetManagesOwnScheduling(managesOwnScheduling *bool) {
	s.ManagesOwnScheduling = managesOwnScheduling
	s.require(systemFieldManagesOwnScheduling)
}

func (s *System) UnmarshalJSON(data []byte) error {
	type unmarshaler System
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = System(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *System) MarshalJSON() ([]byte, error) {
	type embed System
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *System) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// A task represents a structured unit of work that can be assigned to an agent for execution.
//
//	Tasks are the fundamental building blocks of work assignment in the Lattice.
//	Each task has a unique identifier, a specification defining what needs to be done,
//	status information tracking its progress, and various metadata facilitating its lifecycle management.
//
//	Tasks can be related to each other, through parent-child relationships, assigned to
//	specific agents, and tracked through a well-defined state machine from creation to completion.
//	They support rich status reporting, including progress updates, error handling, and results.
var (
	taskFieldVersion             = big.NewInt(1 << 0)
	taskFieldDisplayName         = big.NewInt(1 << 1)
	taskFieldSpecification       = big.NewInt(1 << 2)
	taskFieldCreatedBy           = big.NewInt(1 << 3)
	taskFieldLastUpdatedBy       = big.NewInt(1 << 4)
	taskFieldLastUpdateTime      = big.NewInt(1 << 5)
	taskFieldStatus              = big.NewInt(1 << 6)
	taskFieldScheduledTime       = big.NewInt(1 << 7)
	taskFieldRelations           = big.NewInt(1 << 8)
	taskFieldDescription         = big.NewInt(1 << 9)
	taskFieldIsExecutedElsewhere = big.NewInt(1 << 10)
	taskFieldCreateTime          = big.NewInt(1 << 11)
	taskFieldReplication         = big.NewInt(1 << 12)
	taskFieldInitialEntities     = big.NewInt(1 << 13)
	taskFieldOwner               = big.NewInt(1 << 14)
)

type Task struct {
	// Version of this task.
	Version *TaskVersion `json:"version,omitempty" url:"version,omitempty"`
	// DEPRECATED: Human readable display name for this task, should be short (<100 chars).
	DisplayName *string `json:"displayName,omitempty" url:"displayName,omitempty"`
	// The path for the Protobuf task definition, and the complete task data.
	Specification *GoogleProtobufAny `json:"specification,omitempty" url:"specification,omitempty"`
	// Records who created this task. This field will not change after the task has been created.
	CreatedBy *Principal `json:"createdBy,omitempty" url:"createdBy,omitempty"`
	// Records who updated this task last.
	LastUpdatedBy *Principal `json:"lastUpdatedBy,omitempty" url:"lastUpdatedBy,omitempty"`
	// Records the time of last update.
	LastUpdateTime *time.Time `json:"lastUpdateTime,omitempty" url:"lastUpdateTime,omitempty"`
	// The status of this task.
	Status *TaskStatus `json:"status,omitempty" url:"status,omitempty"`
	// If the task has been scheduled to execute, what time it should execute at.
	ScheduledTime *time.Time `json:"scheduledTime,omitempty" url:"scheduledTime,omitempty"`
	// Any related Tasks associated with this, typically includes an assignee for this task and/or a parent.
	Relations *Relations `json:"relations,omitempty" url:"relations,omitempty"`
	// Longer, free form human readable description of this task
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// If set, execution of this task is managed elsewhere, not by Task Manager.
	//
	//	In other words, task manager will not attempt to update the assigned agent with execution instructions.
	IsExecutedElsewhere *bool `json:"isExecutedElsewhere,omitempty" url:"isExecutedElsewhere,omitempty"`
	// Time of task creation.
	CreateTime *time.Time `json:"createTime,omitempty" url:"createTime,omitempty"`
	// If populated, designates this to be a replicated task.
	Replication *Replication `json:"replication,omitempty" url:"replication,omitempty"`
	// If populated, indicates an initial set of entities that can be used to execute an entity aware task
	//
	//	For example, an entity Objective, an entity Keep In Zone, etc.
	//	These will not be updated during execution. If a taskable agent needs continuous updates on the entities from the
	//	COP, can call entity-manager, or use an AlternateId escape hatch.
	InitialEntities []*TaskEntity `json:"initialEntities,omitempty" url:"initialEntities,omitempty"`
	// The networked owner of this task. It is used to ensure that linear writes occur on the node responsible
	//
	//	for replication of task data to other nodes running Task Manager.
	Owner *Owner `json:"owner,omitempty" url:"owner,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *Task) GetVersion() *TaskVersion {
	if t == nil {
		return nil
	}
	return t.Version
}

func (t *Task) GetDisplayName() *string {
	if t == nil {
		return nil
	}
	return t.DisplayName
}

func (t *Task) GetSpecification() *GoogleProtobufAny {
	if t == nil {
		return nil
	}
	return t.Specification
}

func (t *Task) GetCreatedBy() *Principal {
	if t == nil {
		return nil
	}
	return t.CreatedBy
}

func (t *Task) GetLastUpdatedBy() *Principal {
	if t == nil {
		return nil
	}
	return t.LastUpdatedBy
}

func (t *Task) GetLastUpdateTime() *time.Time {
	if t == nil {
		return nil
	}
	return t.LastUpdateTime
}

func (t *Task) GetStatus() *TaskStatus {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *Task) GetScheduledTime() *time.Time {
	if t == nil {
		return nil
	}
	return t.ScheduledTime
}

func (t *Task) GetRelations() *Relations {
	if t == nil {
		return nil
	}
	return t.Relations
}

func (t *Task) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *Task) GetIsExecutedElsewhere() *bool {
	if t == nil {
		return nil
	}
	return t.IsExecutedElsewhere
}

func (t *Task) GetCreateTime() *time.Time {
	if t == nil {
		return nil
	}
	return t.CreateTime
}

func (t *Task) GetReplication() *Replication {
	if t == nil {
		return nil
	}
	return t.Replication
}

func (t *Task) GetInitialEntities() []*TaskEntity {
	if t == nil {
		return nil
	}
	return t.InitialEntities
}

func (t *Task) GetOwner() *Owner {
	if t == nil {
		return nil
	}
	return t.Owner
}

func (t *Task) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *Task) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetVersion(version *TaskVersion) {
	t.Version = version
	t.require(taskFieldVersion)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetDisplayName(displayName *string) {
	t.DisplayName = displayName
	t.require(taskFieldDisplayName)
}

// SetSpecification sets the Specification field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetSpecification(specification *GoogleProtobufAny) {
	t.Specification = specification
	t.require(taskFieldSpecification)
}

// SetCreatedBy sets the CreatedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetCreatedBy(createdBy *Principal) {
	t.CreatedBy = createdBy
	t.require(taskFieldCreatedBy)
}

// SetLastUpdatedBy sets the LastUpdatedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetLastUpdatedBy(lastUpdatedBy *Principal) {
	t.LastUpdatedBy = lastUpdatedBy
	t.require(taskFieldLastUpdatedBy)
}

// SetLastUpdateTime sets the LastUpdateTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetLastUpdateTime(lastUpdateTime *time.Time) {
	t.LastUpdateTime = lastUpdateTime
	t.require(taskFieldLastUpdateTime)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetStatus(status *TaskStatus) {
	t.Status = status
	t.require(taskFieldStatus)
}

// SetScheduledTime sets the ScheduledTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetScheduledTime(scheduledTime *time.Time) {
	t.ScheduledTime = scheduledTime
	t.require(taskFieldScheduledTime)
}

// SetRelations sets the Relations field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetRelations(relations *Relations) {
	t.Relations = relations
	t.require(taskFieldRelations)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetDescription(description *string) {
	t.Description = description
	t.require(taskFieldDescription)
}

// SetIsExecutedElsewhere sets the IsExecutedElsewhere field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetIsExecutedElsewhere(isExecutedElsewhere *bool) {
	t.IsExecutedElsewhere = isExecutedElsewhere
	t.require(taskFieldIsExecutedElsewhere)
}

// SetCreateTime sets the CreateTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetCreateTime(createTime *time.Time) {
	t.CreateTime = createTime
	t.require(taskFieldCreateTime)
}

// SetReplication sets the Replication field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetReplication(replication *Replication) {
	t.Replication = replication
	t.require(taskFieldReplication)
}

// SetInitialEntities sets the InitialEntities field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetInitialEntities(initialEntities []*TaskEntity) {
	t.InitialEntities = initialEntities
	t.require(taskFieldInitialEntities)
}

// SetOwner sets the Owner field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetOwner(owner *Owner) {
	t.Owner = owner
	t.require(taskFieldOwner)
}

func (t *Task) UnmarshalJSON(data []byte) error {
	type embed Task
	var unmarshaler = struct {
		embed
		LastUpdateTime *internal.DateTime `json:"lastUpdateTime,omitempty"`
		ScheduledTime  *internal.DateTime `json:"scheduledTime,omitempty"`
		CreateTime     *internal.DateTime `json:"createTime,omitempty"`
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = Task(unmarshaler.embed)
	t.LastUpdateTime = unmarshaler.LastUpdateTime.TimePtr()
	t.ScheduledTime = unmarshaler.ScheduledTime.TimePtr()
	t.CreateTime = unmarshaler.CreateTime.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *Task) MarshalJSON() ([]byte, error) {
	type embed Task
	var marshaler = struct {
		embed
		LastUpdateTime *internal.DateTime `json:"lastUpdateTime,omitempty"`
		ScheduledTime  *internal.DateTime `json:"scheduledTime,omitempty"`
		CreateTime     *internal.DateTime `json:"createTime,omitempty"`
	}{
		embed:          embed(*t),
		LastUpdateTime: internal.NewOptionalDateTime(t.LastUpdateTime),
		ScheduledTime:  internal.NewOptionalDateTime(t.ScheduledTime),
		CreateTime:     internal.NewOptionalDateTime(t.CreateTime),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *Task) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// An entity wrapper used in task definitions, with additional metadata.
//
//	TaskEntity wraps an entity reference with additional contextual information for task execution.
//	This structure allows entities to be passed to tasks with supplementary metadata that aids
//	in proper task execution, while also serving as an extension point for future capabilities.
var (
	taskEntityFieldEntity   = big.NewInt(1 << 0)
	taskEntityFieldSnapshot = big.NewInt(1 << 1)
)

type TaskEntity struct {
	// The wrapped entity.
	Entity *Entity `json:"entity,omitempty" url:"entity,omitempty"`
	// Indicates that this entity was generated from a snapshot of a live entity.
	Snapshot *bool `json:"snapshot,omitempty" url:"snapshot,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TaskEntity) GetEntity() *Entity {
	if t == nil {
		return nil
	}
	return t.Entity
}

func (t *TaskEntity) GetSnapshot() *bool {
	if t == nil {
		return nil
	}
	return t.Snapshot
}

func (t *TaskEntity) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TaskEntity) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetEntity sets the Entity field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskEntity) SetEntity(entity *Entity) {
	t.Entity = entity
	t.require(taskEntityFieldEntity)
}

// SetSnapshot sets the Snapshot field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskEntity) SetSnapshot(snapshot *bool) {
	t.Snapshot = snapshot
	t.require(taskEntityFieldSnapshot)
}

func (t *TaskEntity) UnmarshalJSON(data []byte) error {
	type unmarshaler TaskEntity
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TaskEntity(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TaskEntity) MarshalJSON() ([]byte, error) {
	type embed TaskEntity
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TaskEntity) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Error information associated with a task.
//
//	TaskError contains structured error details, including an error code, a human-readable
//	message, and optional extended error information. This structure is used when a task
//	encounters problems during its lifecycle.
var (
	taskErrorFieldCode         = big.NewInt(1 << 0)
	taskErrorFieldMessage      = big.NewInt(1 << 1)
	taskErrorFieldErrorDetails = big.NewInt(1 << 2)
)

type TaskError struct {
	// Error code for task error.
	Code *TaskErrorCode `json:"code,omitempty" url:"code,omitempty"`
	// Descriptive human-readable string regarding this error.
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Any additional details regarding this error.
	ErrorDetails *GoogleProtobufAny `json:"errorDetails,omitempty" url:"errorDetails,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TaskError) GetCode() *TaskErrorCode {
	if t == nil {
		return nil
	}
	return t.Code
}

func (t *TaskError) GetMessage() *string {
	if t == nil {
		return nil
	}
	return t.Message
}

func (t *TaskError) GetErrorDetails() *GoogleProtobufAny {
	if t == nil {
		return nil
	}
	return t.ErrorDetails
}

func (t *TaskError) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TaskError) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskError) SetCode(code *TaskErrorCode) {
	t.Code = code
	t.require(taskErrorFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskError) SetMessage(message *string) {
	t.Message = message
	t.require(taskErrorFieldMessage)
}

// SetErrorDetails sets the ErrorDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskError) SetErrorDetails(errorDetails *GoogleProtobufAny) {
	t.ErrorDetails = errorDetails
	t.require(taskErrorFieldErrorDetails)
}

func (t *TaskError) UnmarshalJSON(data []byte) error {
	type unmarshaler TaskError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TaskError(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TaskError) MarshalJSON() ([]byte, error) {
	type embed TaskError
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TaskError) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Error code for task error.
type TaskErrorCode string

const (
	TaskErrorCodeErrorCodeInvalid   TaskErrorCode = "ERROR_CODE_INVALID"
	TaskErrorCodeErrorCodeCancelled TaskErrorCode = "ERROR_CODE_CANCELLED"
	TaskErrorCodeErrorCodeRejected  TaskErrorCode = "ERROR_CODE_REJECTED"
	TaskErrorCodeErrorCodeTimeout   TaskErrorCode = "ERROR_CODE_TIMEOUT"
	TaskErrorCodeErrorCodeFailed    TaskErrorCode = "ERROR_CODE_FAILED"
)

func NewTaskErrorCodeFromString(s string) (TaskErrorCode, error) {
	switch s {
	case "ERROR_CODE_INVALID":
		return TaskErrorCodeErrorCodeInvalid, nil
	case "ERROR_CODE_CANCELLED":
		return TaskErrorCodeErrorCodeCancelled, nil
	case "ERROR_CODE_REJECTED":
		return TaskErrorCodeErrorCodeRejected, nil
	case "ERROR_CODE_TIMEOUT":
		return TaskErrorCodeErrorCodeTimeout, nil
	case "ERROR_CODE_FAILED":
		return TaskErrorCodeErrorCodeFailed, nil
	}
	var t TaskErrorCode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TaskErrorCode) Ptr() *TaskErrorCode {
	return &t
}

// Response containing tasks that match the query criteria.
//
// This message returns a list of Task objects that satisfy the filter conditions
// specified in the request. When there are more matching tasks than can be returned
// in a single response, a page_token is provided to retrieve the next batch in
// a subsequent request. An empty tasks list with no page_token indicates that
// there are no more matching tasks.
var (
	taskQueryResultsFieldTasks         = big.NewInt(1 << 0)
	taskQueryResultsFieldNextPageToken = big.NewInt(1 << 1)
)

type TaskQueryResults struct {
	Tasks []*Task `json:"tasks,omitempty" url:"tasks,omitempty"`
	// Incomplete results can be detected by a non-empty nextPageToken field in the query results. In order to retrieve
	// the next page, perform the exact same request as previously and append a pageToken field with the value of
	// nextPageToken from the previous page. A new nextPageToken is provided on the following pages until all the
	// results are retrieved.
	NextPageToken *string `json:"nextPageToken,omitempty" url:"nextPageToken,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TaskQueryResults) GetTasks() []*Task {
	if t == nil {
		return nil
	}
	return t.Tasks
}

func (t *TaskQueryResults) GetNextPageToken() *string {
	if t == nil {
		return nil
	}
	return t.NextPageToken
}

func (t *TaskQueryResults) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TaskQueryResults) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTasks sets the Tasks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskQueryResults) SetTasks(tasks []*Task) {
	t.Tasks = tasks
	t.require(taskQueryResultsFieldTasks)
}

// SetNextPageToken sets the NextPageToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskQueryResults) SetNextPageToken(nextPageToken *string) {
	t.NextPageToken = nextPageToken
	t.require(taskQueryResultsFieldNextPageToken)
}

func (t *TaskQueryResults) UnmarshalJSON(data []byte) error {
	type unmarshaler TaskQueryResults
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TaskQueryResults(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TaskQueryResults) MarshalJSON() ([]byte, error) {
	type embed TaskQueryResults
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TaskQueryResults) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Comprehensive status information for a task at a given point in time.
//
//	TaskStatus contains all status-related information for a task, including its current state,
//	any error conditions, progress details, results, timing information, and resource allocations.
//	This object evolves throughout a task's lifecycle, providing increasing detail as the task
//	progresses from creation through execution to completion.
var (
	taskStatusFieldStatus     = big.NewInt(1 << 0)
	taskStatusFieldTaskError  = big.NewInt(1 << 1)
	taskStatusFieldProgress   = big.NewInt(1 << 2)
	taskStatusFieldResult     = big.NewInt(1 << 3)
	taskStatusFieldStartTime  = big.NewInt(1 << 4)
	taskStatusFieldEstimate   = big.NewInt(1 << 5)
	taskStatusFieldAllocation = big.NewInt(1 << 6)
)

type TaskStatus struct {
	// Status of the task.
	Status *TaskStatusStatus `json:"status,omitempty" url:"status,omitempty"`
	// Any errors associated with the task.
	TaskError *TaskError `json:"taskError,omitempty" url:"taskError,omitempty"`
	// Any incremental progress on the task, should be from the tasks/v* /progress folder.
	Progress *GoogleProtobufAny `json:"progress,omitempty" url:"progress,omitempty"`
	// Any final result of the task, should be from tasks/v* /result folder.
	Result *GoogleProtobufAny `json:"result,omitempty" url:"result,omitempty"`
	// Time the task began execution, may not be known even for executing Tasks.
	StartTime *time.Time `json:"startTime,omitempty" url:"startTime,omitempty"`
	// Any estimate for how the task will progress, should be from tasks/v* /estimates folder.
	Estimate *GoogleProtobufAny `json:"estimate,omitempty" url:"estimate,omitempty"`
	// Any allocated agents of the task.
	Allocation *Allocation `json:"allocation,omitempty" url:"allocation,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TaskStatus) GetStatus() *TaskStatusStatus {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *TaskStatus) GetTaskError() *TaskError {
	if t == nil {
		return nil
	}
	return t.TaskError
}

func (t *TaskStatus) GetProgress() *GoogleProtobufAny {
	if t == nil {
		return nil
	}
	return t.Progress
}

func (t *TaskStatus) GetResult() *GoogleProtobufAny {
	if t == nil {
		return nil
	}
	return t.Result
}

func (t *TaskStatus) GetStartTime() *time.Time {
	if t == nil {
		return nil
	}
	return t.StartTime
}

func (t *TaskStatus) GetEstimate() *GoogleProtobufAny {
	if t == nil {
		return nil
	}
	return t.Estimate
}

func (t *TaskStatus) GetAllocation() *Allocation {
	if t == nil {
		return nil
	}
	return t.Allocation
}

func (t *TaskStatus) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TaskStatus) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskStatus) SetStatus(status *TaskStatusStatus) {
	t.Status = status
	t.require(taskStatusFieldStatus)
}

// SetTaskError sets the TaskError field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskStatus) SetTaskError(taskError *TaskError) {
	t.TaskError = taskError
	t.require(taskStatusFieldTaskError)
}

// SetProgress sets the Progress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskStatus) SetProgress(progress *GoogleProtobufAny) {
	t.Progress = progress
	t.require(taskStatusFieldProgress)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskStatus) SetResult(result *GoogleProtobufAny) {
	t.Result = result
	t.require(taskStatusFieldResult)
}

// SetStartTime sets the StartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskStatus) SetStartTime(startTime *time.Time) {
	t.StartTime = startTime
	t.require(taskStatusFieldStartTime)
}

// SetEstimate sets the Estimate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskStatus) SetEstimate(estimate *GoogleProtobufAny) {
	t.Estimate = estimate
	t.require(taskStatusFieldEstimate)
}

// SetAllocation sets the Allocation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskStatus) SetAllocation(allocation *Allocation) {
	t.Allocation = allocation
	t.require(taskStatusFieldAllocation)
}

func (t *TaskStatus) UnmarshalJSON(data []byte) error {
	type embed TaskStatus
	var unmarshaler = struct {
		embed
		StartTime *internal.DateTime `json:"startTime,omitempty"`
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TaskStatus(unmarshaler.embed)
	t.StartTime = unmarshaler.StartTime.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TaskStatus) MarshalJSON() ([]byte, error) {
	type embed TaskStatus
	var marshaler = struct {
		embed
		StartTime *internal.DateTime `json:"startTime,omitempty"`
	}{
		embed:     embed(*t),
		StartTime: internal.NewOptionalDateTime(t.StartTime),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TaskStatus) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Status of the task.
type TaskStatusStatus string

const (
	TaskStatusStatusStatusInvalid            TaskStatusStatus = "STATUS_INVALID"
	TaskStatusStatusStatusCreated            TaskStatusStatus = "STATUS_CREATED"
	TaskStatusStatusStatusScheduledInManager TaskStatusStatus = "STATUS_SCHEDULED_IN_MANAGER"
	TaskStatusStatusStatusSent               TaskStatusStatus = "STATUS_SENT"
	TaskStatusStatusStatusMachineReceipt     TaskStatusStatus = "STATUS_MACHINE_RECEIPT"
	TaskStatusStatusStatusAck                TaskStatusStatus = "STATUS_ACK"
	TaskStatusStatusStatusWilco              TaskStatusStatus = "STATUS_WILCO"
	TaskStatusStatusStatusExecuting          TaskStatusStatus = "STATUS_EXECUTING"
	TaskStatusStatusStatusWaitingForUpdate   TaskStatusStatus = "STATUS_WAITING_FOR_UPDATE"
	TaskStatusStatusStatusDoneOk             TaskStatusStatus = "STATUS_DONE_OK"
	TaskStatusStatusStatusDoneNotOk          TaskStatusStatus = "STATUS_DONE_NOT_OK"
	TaskStatusStatusStatusReplaced           TaskStatusStatus = "STATUS_REPLACED"
	TaskStatusStatusStatusCancelRequested    TaskStatusStatus = "STATUS_CANCEL_REQUESTED"
	TaskStatusStatusStatusCompleteRequested  TaskStatusStatus = "STATUS_COMPLETE_REQUESTED"
	TaskStatusStatusStatusVersionRejected    TaskStatusStatus = "STATUS_VERSION_REJECTED"
)

func NewTaskStatusStatusFromString(s string) (TaskStatusStatus, error) {
	switch s {
	case "STATUS_INVALID":
		return TaskStatusStatusStatusInvalid, nil
	case "STATUS_CREATED":
		return TaskStatusStatusStatusCreated, nil
	case "STATUS_SCHEDULED_IN_MANAGER":
		return TaskStatusStatusStatusScheduledInManager, nil
	case "STATUS_SENT":
		return TaskStatusStatusStatusSent, nil
	case "STATUS_MACHINE_RECEIPT":
		return TaskStatusStatusStatusMachineReceipt, nil
	case "STATUS_ACK":
		return TaskStatusStatusStatusAck, nil
	case "STATUS_WILCO":
		return TaskStatusStatusStatusWilco, nil
	case "STATUS_EXECUTING":
		return TaskStatusStatusStatusExecuting, nil
	case "STATUS_WAITING_FOR_UPDATE":
		return TaskStatusStatusStatusWaitingForUpdate, nil
	case "STATUS_DONE_OK":
		return TaskStatusStatusStatusDoneOk, nil
	case "STATUS_DONE_NOT_OK":
		return TaskStatusStatusStatusDoneNotOk, nil
	case "STATUS_REPLACED":
		return TaskStatusStatusStatusReplaced, nil
	case "STATUS_CANCEL_REQUESTED":
		return TaskStatusStatusStatusCancelRequested, nil
	case "STATUS_COMPLETE_REQUESTED":
		return TaskStatusStatusStatusCompleteRequested, nil
	case "STATUS_VERSION_REJECTED":
		return TaskStatusStatusStatusVersionRejected, nil
	}
	var t TaskStatusStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TaskStatusStatus) Ptr() *TaskStatusStatus {
	return &t
}

// Versioning information for a task.
//
//	TaskVersion provides a unique identifier for each task, along with separate version counters
//	for tracking changes to the task's definition and its status. This versioning system enables
//	optimistic concurrency control, ensuring that updates from multiple sources don't conflict.
var (
	taskVersionFieldTaskID            = big.NewInt(1 << 0)
	taskVersionFieldDefinitionVersion = big.NewInt(1 << 1)
	taskVersionFieldStatusVersion     = big.NewInt(1 << 2)
)

type TaskVersion struct {
	// The unique identifier for this task, used to distinguish it from all other tasks in the system.
	TaskID *string `json:"taskId,omitempty" url:"taskId,omitempty"`
	// Counter that increments on changes to the task definition.
	//
	//	Unset (0) initially, starts at 1 on creation, and increments with each update to task fields.
	DefinitionVersion *int `json:"definitionVersion,omitempty" url:"definitionVersion,omitempty"`
	// Counter that increments on changes to TaskStatus.
	//
	//	Unset (0) initially, starts at 1 on creation, and increments with each status update.
	StatusVersion *int `json:"statusVersion,omitempty" url:"statusVersion,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TaskVersion) GetTaskID() *string {
	if t == nil {
		return nil
	}
	return t.TaskID
}

func (t *TaskVersion) GetDefinitionVersion() *int {
	if t == nil {
		return nil
	}
	return t.DefinitionVersion
}

func (t *TaskVersion) GetStatusVersion() *int {
	if t == nil {
		return nil
	}
	return t.StatusVersion
}

func (t *TaskVersion) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TaskVersion) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTaskID sets the TaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskVersion) SetTaskID(taskID *string) {
	t.TaskID = taskID
	t.require(taskVersionFieldTaskID)
}

// SetDefinitionVersion sets the DefinitionVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskVersion) SetDefinitionVersion(definitionVersion *int) {
	t.DefinitionVersion = definitionVersion
	t.require(taskVersionFieldDefinitionVersion)
}

// SetStatusVersion sets the StatusVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskVersion) SetStatusVersion(statusVersion *int) {
	t.StatusVersion = statusVersion
	t.require(taskVersionFieldStatusVersion)
}

func (t *TaskVersion) UnmarshalJSON(data []byte) error {
	type unmarshaler TaskVersion
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TaskVersion(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TaskVersion) MarshalJSON() ([]byte, error) {
	type embed TaskVersion
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TaskVersion) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// A User Principal representing a human.
var (
	userFieldUserID = big.NewInt(1 << 0)
)

type User struct {
	// The User ID associated with this User.
	UserID *string `json:"userId,omitempty" url:"userId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *User) GetUserID() *string {
	if u == nil {
		return nil
	}
	return u.UserID
}

func (u *User) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *User) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *User) SetUserID(userID *string) {
	u.UserID = userID
	u.require(userFieldUserID)
}

func (u *User) UnmarshalJSON(data []byte) error {
	type unmarshaler User
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = User(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *User) MarshalJSON() ([]byte, error) {
	type embed User
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *User) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	taskQueryStatusFilterFieldStatus = big.NewInt(1 << 0)
)

type TaskQueryStatusFilter struct {
	// Status of the Task to filter by, inclusive.
	Status *TaskQueryStatusFilterStatus `json:"status,omitempty" url:"status,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TaskQueryStatusFilter) GetStatus() *TaskQueryStatusFilterStatus {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *TaskQueryStatusFilter) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TaskQueryStatusFilter) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskQueryStatusFilter) SetStatus(status *TaskQueryStatusFilterStatus) {
	t.Status = status
	t.require(taskQueryStatusFilterFieldStatus)
}

func (t *TaskQueryStatusFilter) UnmarshalJSON(data []byte) error {
	type unmarshaler TaskQueryStatusFilter
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TaskQueryStatusFilter(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TaskQueryStatusFilter) MarshalJSON() ([]byte, error) {
	type embed TaskQueryStatusFilter
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TaskQueryStatusFilter) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Status of the Task to filter by, inclusive.
type TaskQueryStatusFilterStatus string

const (
	TaskQueryStatusFilterStatusStatusInvalid            TaskQueryStatusFilterStatus = "STATUS_INVALID"
	TaskQueryStatusFilterStatusStatusCreated            TaskQueryStatusFilterStatus = "STATUS_CREATED"
	TaskQueryStatusFilterStatusStatusScheduledInManager TaskQueryStatusFilterStatus = "STATUS_SCHEDULED_IN_MANAGER"
	TaskQueryStatusFilterStatusStatusSent               TaskQueryStatusFilterStatus = "STATUS_SENT"
	TaskQueryStatusFilterStatusStatusMachineReceipt     TaskQueryStatusFilterStatus = "STATUS_MACHINE_RECEIPT"
	TaskQueryStatusFilterStatusStatusAck                TaskQueryStatusFilterStatus = "STATUS_ACK"
	TaskQueryStatusFilterStatusStatusWilco              TaskQueryStatusFilterStatus = "STATUS_WILCO"
	TaskQueryStatusFilterStatusStatusExecuting          TaskQueryStatusFilterStatus = "STATUS_EXECUTING"
	TaskQueryStatusFilterStatusStatusWaitingForUpdate   TaskQueryStatusFilterStatus = "STATUS_WAITING_FOR_UPDATE"
	TaskQueryStatusFilterStatusStatusDoneOk             TaskQueryStatusFilterStatus = "STATUS_DONE_OK"
	TaskQueryStatusFilterStatusStatusDoneNotOk          TaskQueryStatusFilterStatus = "STATUS_DONE_NOT_OK"
	TaskQueryStatusFilterStatusStatusReplaced           TaskQueryStatusFilterStatus = "STATUS_REPLACED"
	TaskQueryStatusFilterStatusStatusCancelRequested    TaskQueryStatusFilterStatus = "STATUS_CANCEL_REQUESTED"
	TaskQueryStatusFilterStatusStatusCompleteRequested  TaskQueryStatusFilterStatus = "STATUS_COMPLETE_REQUESTED"
	TaskQueryStatusFilterStatusStatusVersionRejected    TaskQueryStatusFilterStatus = "STATUS_VERSION_REJECTED"
)

func NewTaskQueryStatusFilterStatusFromString(s string) (TaskQueryStatusFilterStatus, error) {
	switch s {
	case "STATUS_INVALID":
		return TaskQueryStatusFilterStatusStatusInvalid, nil
	case "STATUS_CREATED":
		return TaskQueryStatusFilterStatusStatusCreated, nil
	case "STATUS_SCHEDULED_IN_MANAGER":
		return TaskQueryStatusFilterStatusStatusScheduledInManager, nil
	case "STATUS_SENT":
		return TaskQueryStatusFilterStatusStatusSent, nil
	case "STATUS_MACHINE_RECEIPT":
		return TaskQueryStatusFilterStatusStatusMachineReceipt, nil
	case "STATUS_ACK":
		return TaskQueryStatusFilterStatusStatusAck, nil
	case "STATUS_WILCO":
		return TaskQueryStatusFilterStatusStatusWilco, nil
	case "STATUS_EXECUTING":
		return TaskQueryStatusFilterStatusStatusExecuting, nil
	case "STATUS_WAITING_FOR_UPDATE":
		return TaskQueryStatusFilterStatusStatusWaitingForUpdate, nil
	case "STATUS_DONE_OK":
		return TaskQueryStatusFilterStatusStatusDoneOk, nil
	case "STATUS_DONE_NOT_OK":
		return TaskQueryStatusFilterStatusStatusDoneNotOk, nil
	case "STATUS_REPLACED":
		return TaskQueryStatusFilterStatusStatusReplaced, nil
	case "STATUS_CANCEL_REQUESTED":
		return TaskQueryStatusFilterStatusStatusCancelRequested, nil
	case "STATUS_COMPLETE_REQUESTED":
		return TaskQueryStatusFilterStatusStatusCompleteRequested, nil
	case "STATUS_VERSION_REJECTED":
		return TaskQueryStatusFilterStatusStatusVersionRejected, nil
	}
	var t TaskQueryStatusFilterStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TaskQueryStatusFilterStatus) Ptr() *TaskQueryStatusFilterStatus {
	return &t
}

// If provided, only provides Tasks updated within the time range.
var (
	taskQueryUpdateTimeRangeFieldStartTime = big.NewInt(1 << 0)
	taskQueryUpdateTimeRangeFieldEndTime   = big.NewInt(1 << 1)
)

type TaskQueryUpdateTimeRange struct {
	// If provided, returns Tasks only updated after this time.
	StartTime *string `json:"startTime,omitempty" url:"startTime,omitempty"`
	// If provided, returns Tasks only updated before this time.
	EndTime *string `json:"endTime,omitempty" url:"endTime,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TaskQueryUpdateTimeRange) GetStartTime() *string {
	if t == nil {
		return nil
	}
	return t.StartTime
}

func (t *TaskQueryUpdateTimeRange) GetEndTime() *string {
	if t == nil {
		return nil
	}
	return t.EndTime
}

func (t *TaskQueryUpdateTimeRange) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TaskQueryUpdateTimeRange) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetStartTime sets the StartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskQueryUpdateTimeRange) SetStartTime(startTime *string) {
	t.StartTime = startTime
	t.require(taskQueryUpdateTimeRangeFieldStartTime)
}

// SetEndTime sets the EndTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskQueryUpdateTimeRange) SetEndTime(endTime *string) {
	t.EndTime = endTime
	t.require(taskQueryUpdateTimeRangeFieldEndTime)
}

func (t *TaskQueryUpdateTimeRange) UnmarshalJSON(data []byte) error {
	type unmarshaler TaskQueryUpdateTimeRange
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TaskQueryUpdateTimeRange(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TaskQueryUpdateTimeRange) MarshalJSON() ([]byte, error) {
	type embed TaskQueryUpdateTimeRange
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TaskQueryUpdateTimeRange) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	taskStatusUpdateFieldTaskID        = big.NewInt(1 << 0)
	taskStatusUpdateFieldStatusVersion = big.NewInt(1 << 1)
	taskStatusUpdateFieldNewStatus     = big.NewInt(1 << 2)
	taskStatusUpdateFieldAuthor        = big.NewInt(1 << 3)
)

type TaskStatusUpdate struct {
	// ID of task to update status of
	TaskID string `json:"-" url:"-"`
	// The status version of the task to update. This version number increments to indicate the task's
	// current stage in its status lifecycle. Specifically, whenever a task's status updates, the status
	// version increments by one. Any status updates received with a lower status version number than what
	// is known are considered stale and ignored.
	StatusVersion *int `json:"statusVersion,omitempty" url:"-"`
	// The new status of the task.
	NewStatus *TaskStatus `json:"newStatus,omitempty" url:"-"`
	Author    *Principal  `json:"author,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TaskStatusUpdate) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTaskID sets the TaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskStatusUpdate) SetTaskID(taskID string) {
	t.TaskID = taskID
	t.require(taskStatusUpdateFieldTaskID)
}

// SetStatusVersion sets the StatusVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskStatusUpdate) SetStatusVersion(statusVersion *int) {
	t.StatusVersion = statusVersion
	t.require(taskStatusUpdateFieldStatusVersion)
}

// SetNewStatus sets the NewStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskStatusUpdate) SetNewStatus(newStatus *TaskStatus) {
	t.NewStatus = newStatus
	t.require(taskStatusUpdateFieldNewStatus)
}

// SetAuthor sets the Author field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskStatusUpdate) SetAuthor(author *Principal) {
	t.Author = author
	t.require(taskStatusUpdateFieldAuthor)
}
