// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/anduril/lattice-sdk-go/v5/core"
	entities "github.com/anduril/lattice-sdk-go/v5/entity/entities"
	oauth2 "github.com/anduril/lattice-sdk-go/v5/entity/oauth2"
	internal "github.com/anduril/lattice-sdk-go/v5/internal"
)

type Client struct {
	OAuth2   *oauth2.Client
	Entities *entities.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		OAuth2:   oauth2.NewClient(options),
		Entities: entities.NewClient(options),
		options:  options,
		baseURL:  options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
