// Code generated by Fern. DO NOT EDIT.

package oauth2

import (
	context "context"
	Lattice "github.com/anduril/lattice-sdk-go"
	core "github.com/anduril/lattice-sdk-go/core"
	internal "github.com/anduril/lattice-sdk-go/internal"
	option "github.com/anduril/lattice-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Exchange authorization code, refresh token, client credentials, or resource owner credentials for an access token
func (c *Client) GetToken(
	ctx context.Context,
	request *Lattice.GetTokenRequest,
	opts ...option.RequestOption,
) (*Lattice.GetTokenResponse, error) {
	response, err := c.WithRawResponse.GetToken(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
