// Code generated by Fern. DO NOT EDIT.

package oauth2

import (
	context "context"
	Lattice "github.com/anduril/lattice-sdk-go/v4"
	core "github.com/anduril/lattice-sdk-go/v4/core"
	internal "github.com/anduril/lattice-sdk-go/v4/internal"
	option "github.com/anduril/lattice-sdk-go/v4/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) GetToken(
	ctx context.Context,
	request *Lattice.GetTokenRequest,
	opts ...option.RequestOption,
) (*core.Response[*Lattice.GetTokenResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://example.developer.anduril.com",
	)
	endpointURL := baseURL + "/api/v1/oauth/token"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/x-www-form-urlencoded")
	var response *Lattice.GetTokenResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(Lattice.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*Lattice.GetTokenResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
