// Code generated by Fern. DO NOT EDIT.

package entities

import (
	context "context"
	Lattice "github.com/anduril/lattice-sdk-go"
	core "github.com/anduril/lattice-sdk-go/core"
	internal "github.com/anduril/lattice-sdk-go/internal"
	option "github.com/anduril/lattice-sdk-go/option"
	http "net/http"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Publish an entity for ingest into the Entities API. Entities created with this method are "owned" by the originator: other sources,
// such as the UI, may not edit or delete these entities. The server validates entities at API call time and
// returns an error if the entity is invalid.
//
// An entity ID must be provided when calling this endpoint. If the entity referenced by the entity ID does not exist
// then it will be created. Otherwise the entity will be updated. An entity will only be updated if its
// provenance.sourceUpdateTime is greater than the provenance.sourceUpdateTime of the existing entity.
func (c *Client) PublishEntity(
	ctx context.Context,
	request *Lattice.Entity,
	opts ...option.RequestOption,
) (*Lattice.Entity, error) {
	response, err := c.WithRawResponse.PublishEntity(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetEntity(
	ctx context.Context,
	request *Lattice.GetEntityRequest,
	opts ...option.RequestOption,
) (*Lattice.Entity, error) {
	response, err := c.WithRawResponse.GetEntity(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Only fields marked with overridable can be overridden. Please refer to our documentation to see the comprehensive
// list of fields that can be overridden. The entity in the request body should only have a value set on the field
// specified in the field path parameter. Field paths are rooted in the base entity object and must be represented
// using lower_snake_case. Do not include "entity" in the field path.
//
// Note that overrides are applied in an eventually consistent manner. If multiple overrides are created
// concurrently for the same field path, the last writer wins.
func (c *Client) OverrideEntity(
	ctx context.Context,
	request *Lattice.EntityOverride,
	opts ...option.RequestOption,
) (*Lattice.Entity, error) {
	response, err := c.WithRawResponse.OverrideEntity(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This operation clears the override value from the specified field path on the entity.
func (c *Client) RemoveEntityOverride(
	ctx context.Context,
	request *Lattice.RemoveEntityOverrideRequest,
	opts ...option.RequestOption,
) (*Lattice.Entity, error) {
	response, err := c.WithRawResponse.RemoveEntityOverride(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This is a long polling API that will first return all pre-existing data and then return all new data as
// it becomes available. If you want to start a new polling session then open a request with an empty
// 'sessionToken' in the request body. The server will return a new session token in the response.
// If you want to retrieve the next batch of results from an existing polling session then send the session
// token you received from the server in the request body. If no new data is available then the server will
// hold the connection open for up to 5 minutes. After the 5 minute timeout period, the server will close the
// connection with no results and you may resume polling with the same session token. If your session falls behind
// more than 3x the total number of entities in the environment, the server will terminate your session.
// In this case you must start a new session by sending a request with an empty session token.
func (c *Client) LongPollEntityEvents(
	ctx context.Context,
	request *Lattice.EntityEventRequest,
	opts ...option.RequestOption,
) (*Lattice.EntityEventResponse, error) {
	response, err := c.WithRawResponse.LongPollEntityEvents(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Establishes a server-sent events (SSE) connection that streams entity data in real-time.
// This is a one-way connection from server to client that follows the SSE protocol with text/event-stream content type.
//
// This endpoint enables clients to maintain a real-time view of the common operational picture (COP)
// by first streaming all pre-existing entities that match filter criteria, then continuously delivering
// updates as entities are created, modified, or deleted.
//
// The server first sends events with type PREEXISTING for all live entities matching the filter that existed before the stream was open,
// then streams CREATE events for newly created entities, UPDATE events when existing entities change, and DELETED events when entities are removed. The stream remains open
// indefinitely unless preExistingOnly is set to true.
//
// Heartbeat messages can be configured to maintain connection health and detect disconnects by setting the heartbeatIntervalMS
// parameter. These heartbeats help keep the connection alive and allow clients to verify the server is still responsive.
//
// Clients can optimize bandwidth usage by specifying which entity components they need populated using the componentsToInclude parameter.
// This allows receiving only relevant data instead of complete entities.
//
// The connection automatically recovers from temporary disconnections, resuming the stream where it left off. Unlike polling approaches,
// this provides real-time updates with minimal latency and reduced server load.
func (c *Client) StreamEntities(
	ctx context.Context,
	request *Lattice.EntityStreamRequest,
	opts ...option.RequestOption,
) (*core.Stream[Lattice.StreamEntitiesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://example.developer.anduril.com",
	)
	endpointURL := baseURL + "/api/v1/entities/stream"
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Accept", "text/event-stream")
	headers.Add("Content-Type", "application/json")
	streamer := internal.NewStreamer[Lattice.StreamEntitiesResponse](c.caller)
	return streamer.Stream(
		ctx,
		&internal.StreamParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Prefix:          internal.DefaultSSEDataPrefix,
			Terminator:      internal.DefaultSSETerminator,
			Format:          core.StreamFormatSSE,
			Request:         request,
			ErrorDecoder:    internal.NewErrorDecoder(Lattice.ErrorCodes),
		},
	)
}
