// Code generated by Fern. DO NOT EDIT.

package task_tasks_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	client "github.com/anduril/lattice-sdk-go/v5/client"
	option "github.com/anduril/lattice-sdk-go/v5/option"
	task "github.com/anduril/lattice-sdk-go/v5/task"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestTaskTasksCreateTaskWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &task.TaskCreation{}
	_, invocationErr := client.Task.Tasks.CreateTask(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTaskTasksCreateTaskWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTaskTasksCreateTaskWithWireMock", "POST", "/api/v1/tasks", nil, 1)
}

func TestTaskTasksGetTaskWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &task.GetTaskRequest{
		TaskID: "taskId",
	}
	_, invocationErr := client.Task.Tasks.GetTask(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTaskTasksGetTaskWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTaskTasksGetTaskWithWireMock", "GET", "/api/v1/tasks/taskId", nil, 1)
}

func TestTaskTasksUpdateTaskStatusWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &task.TaskStatusUpdate{
		TaskID: "taskId",
	}
	_, invocationErr := client.Task.Tasks.UpdateTaskStatus(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTaskTasksUpdateTaskStatusWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTaskTasksUpdateTaskStatusWithWireMock", "PUT", "/api/v1/tasks/taskId/status", nil, 1)
}

func TestTaskTasksQueryTasksWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &task.TaskQuery{}
	_, invocationErr := client.Task.Tasks.QueryTasks(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTaskTasksQueryTasksWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTaskTasksQueryTasksWithWireMock", "POST", "/api/v1/tasks/query", nil, 1)
}

func TestTaskTasksListenAsAgentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &task.AgentListener{}
	_, invocationErr := client.Task.Tasks.ListenAsAgent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTaskTasksListenAsAgentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTaskTasksListenAsAgentWithWireMock", "POST", "/api/v1/agent/listen", nil, 1)
}
