// Code generated by Fern. DO NOT EDIT.

package oauth

import (
	context "context"
	Lattice "github.com/anduril/lattice-sdk-go/v4"
	core "github.com/anduril/lattice-sdk-go/v4/core"
	internal "github.com/anduril/lattice-sdk-go/v4/internal"
	option "github.com/anduril/lattice-sdk-go/v4/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Gets a new short-lived token using the specified client credentials
func (c *Client) GetToken(
	ctx context.Context,
	request *Lattice.GetTokenRequest,
	opts ...option.RequestOption,
) (*Lattice.GetTokenResponse, error) {
	response, err := c.WithRawResponse.GetToken(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
