// Code generated by Fern. DO NOT EDIT.

package entity_entities_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	client "github.com/anduril/lattice-sdk-go/v5/client"
	entity "github.com/anduril/lattice-sdk-go/v5/entity"
	option "github.com/anduril/lattice-sdk-go/v5/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestEntityEntitiesPublishEntityWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &entity.Entity{}
	_, invocationErr := client.Entity.Entities.PublishEntity(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEntityEntitiesPublishEntityWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEntityEntitiesPublishEntityWithWireMock", "PUT", "/api/v1/entities", nil, 1)
}

func TestEntityEntitiesGetEntityWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &entity.GetEntityRequest{
		EntityID: "entityId",
	}
	_, invocationErr := client.Entity.Entities.GetEntity(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEntityEntitiesGetEntityWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEntityEntitiesGetEntityWithWireMock", "GET", "/api/v1/entities/entityId", nil, 1)
}

func TestEntityEntitiesOverrideEntityWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &entity.EntityOverride{
		EntityID:  "entityId",
		FieldPath: "mil_view.disposition",
	}
	_, invocationErr := client.Entity.Entities.OverrideEntity(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEntityEntitiesOverrideEntityWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEntityEntitiesOverrideEntityWithWireMock", "PUT", "/api/v1/entities/entityId/override/mil_view.disposition", nil, 1)
}

func TestEntityEntitiesRemoveEntityOverrideWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &entity.RemoveEntityOverrideRequest{
		EntityID:  "entityId",
		FieldPath: "mil_view.disposition",
	}
	_, invocationErr := client.Entity.Entities.RemoveEntityOverride(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEntityEntitiesRemoveEntityOverrideWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEntityEntitiesRemoveEntityOverrideWithWireMock", "DELETE", "/api/v1/entities/entityId/override/mil_view.disposition", nil, 1)
}

func TestEntityEntitiesLongPollEntityEventsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &entity.EntityEventRequest{
		SessionToken: "sessionToken",
	}
	_, invocationErr := client.Entity.Entities.LongPollEntityEvents(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEntityEntitiesLongPollEntityEventsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEntityEntitiesLongPollEntityEventsWithWireMock", "POST", "/api/v1/entities/events", nil, 1)
}

func TestEntityEntitiesStreamEntitiesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &entity.EntityStreamRequest{}
	_, invocationErr := client.Entity.Entities.StreamEntities(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEntityEntitiesStreamEntitiesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEntityEntitiesStreamEntitiesWithWireMock", "POST", "/api/v1/entities/stream", nil, 1)
}
